const { BrowserWindow, session, shell } = require('electron');
const path = require('path');
const config = require('../config');
const { createTray, rebuildMenu } = require('../tray');
const windowState = require('./windowState');
const {
  isAuthUrl,
  isAvdUrl,
  isSafeExternalUrl,
  isLikelyAuthPopup,
  parseUaVersions,
  clearAvdSessionState,
  stripCspReportOnly,
  handleRenderProcessGone,
  createAboutBlankInterceptor,
} = require('./helpers');
const { configurePermissionHandlers } = require('../permissions');

const avdWindows = new Set();

const AUTH_CLEAR_ORIGINS = [
  'https://login.microsoftonline.com',
  'https://login.live.com',
  'https://login.microsoft.com',
  'https://account.live.com',
  'https://aadcdn.msftauth.net',
  'https://autologon.microsoftazuread-sso.com',
  'https://microsoftonline.com',
];

async function clearAuthState(appSession) {
  await Promise.all([
    appSession.clearStorageData({ storages: ['cookies'] }),
    appSession.clearStorageData({
      storages: ['localstorage', 'indexeddb', 'sessionstorage', 'serviceworkers', 'cachestorage'],
      origins: AUTH_CLEAR_ORIGINS,
    }),
    appSession.clearAuthCache(),
    appSession.clearCache(),
  ]);
}

function createAvdWindow(url) {
  const win = new BrowserWindow({
    width: config.window.width,
    height: config.window.height,
    minWidth: config.window.minWidth,
    minHeight: config.window.minHeight,
    title: 'Windows App — Session',
    backgroundColor: '#000000',
    autoHideMenuBar: true,
    webPreferences: {
      partition: config.sessionPartition,
      preload: path.join(__dirname, '../browser/preload.js'),
      contextIsolation: false,
      sandbox: false,
      nodeIntegration: false,
      webSecurity: true,
      spellcheck: false,
    },
  });

  win.webContents.setWindowOpenHandler(({ url: newUrl, features, disposition }) => {
    if (!newUrl || newUrl === 'about:blank') return { action: 'deny' };
    if (isAvdUrl(newUrl)) {
      createAvdWindow(newUrl);
      return { action: 'deny' };
    }
    if (isSafeExternalUrl(newUrl) && isLikelyAuthPopup(features, disposition)) {
      return {
        action: 'allow',
        overrideBrowserWindowOptions: {
          modal: true,
          parent: win,
          width: 520,
          height: 700,
          webPreferences: {
            partition: config.sessionPartition,
            contextIsolation: false,
            sandbox: false,
            nodeIntegration: false,
          },
        },
      };
    }
    if (isSafeExternalUrl(newUrl)) shell.openExternal(newUrl);
    return { action: 'deny' };
  });

  win.webContents.on('will-prevent-unload', (event) => event.preventDefault());

  avdWindows.add(win);
  rebuildMenu();

  win.webContents.on('page-title-updated', (_e, title) => {
    if (title) win.setTitle(title);
    rebuildMenu();
  });

  win.on('closed', () => {
    avdWindows.delete(win);
    rebuildMenu();
  });

  // Only clear stale RDP state when this is the sole AVD window — with other
  // sessions open, clearing session-wide storage would corrupt their state too.
  if (avdWindows.size === 1) {
    const avdSession = session.fromPartition(config.sessionPartition);
    clearAvdSessionState(avdSession).finally(() => {
      win.loadURL(url, { userAgent: config.userAgent });
    });
  } else {
    win.loadURL(url, { userAgent: config.userAgent });
  }

  return win;
}

let mainWindow = null;
let appSession = null;

async function clearSession() {
  if (appSession) await clearAuthState(appSession);
}

async function createMainWindow() {
  appSession = session.fromPartition(config.sessionPartition);
  appSession.setUserAgent(config.userAgent);

  configurePermissionHandlers(appSession);

  // Spoof Client Hints request headers — sec-ch-ua is generated by Chromium independently of setUserAgent()
  const { edge: edgeVersion, chrome: chromeVersion } = parseUaVersions(config.userAgent);
  appSession.webRequest.onBeforeSendHeaders((details, callback) => {
    const headers = { ...details.requestHeaders };
    headers['sec-ch-ua'] = `"Microsoft Edge";v="${edgeVersion}", "Not_A Brand";v="99", "Chromium";v="${chromeVersion}"`;
    headers['sec-ch-ua-platform'] = '"Windows"';
    headers['sec-ch-ua-mobile'] = '?0';
    headers['sec-ch-ua-platform-version'] = '"15.0.0"';
    callback({ requestHeaders: headers });
  });

  appSession.webRequest.onHeadersReceived((details, callback) => {
    callback({ responseHeaders: stripCspReportOnly(details.responseHeaders) });
  });

  const aboutBlankHandler = createAboutBlankInterceptor(url => shell.openExternal(url));
  appSession.webRequest.onBeforeRequest(aboutBlankHandler);

  const savedState = windowState.load(config.window);

  mainWindow = new BrowserWindow({
    ...savedState,
    title: 'Windows App',
    backgroundColor: '#1a1a2e',
    autoHideMenuBar: true,
    webPreferences: {
      partition: config.sessionPartition,
      preload: path.join(__dirname, '../browser/preload.js'),
      contextIsolation: false,
      sandbox: false,
      nodeIntegration: false,
      webSecurity: true,
      spellcheck: false,
    },
  });

  mainWindow.webContents.setWindowOpenHandler(({ url, features, disposition }) => {
    if (!url || url === 'about:blank' || url === 'about:blank#blocked') {
      return { action: 'deny' };
    }
    if (isAvdUrl(url)) {
      createAvdWindow(url);
      return { action: 'deny' };
    }
    if (isAuthUrl(url) || (isSafeExternalUrl(url) && isLikelyAuthPopup(features, disposition))) {
      return {
        action: 'allow',
        overrideBrowserWindowOptions: {
          modal: true,
          parent: mainWindow,
          width: 520,
          height: 700,
          webPreferences: {
            partition: config.sessionPartition,
            contextIsolation: false,
            sandbox: false,
            nodeIntegration: false,
          },
        },
      };
    }
    if (isSafeExternalUrl(url)) shell.openExternal(url);
    return { action: 'deny' };
  });

  createTray(() => mainWindow, () => [...avdWindows]);

  if (savedState.isMaximized) mainWindow.maximize();

  mainWindow.on('close', (event) => {
    windowState.save(mainWindow);
    if (!mainWindow.forceClose) {
      event.preventDefault();
      mainWindow.hide();
    }
  });

  mainWindow.loadURL(config.url, { userAgent: config.userAgent });

  mainWindow.webContents.on('render-process-gone', (_event, details) => {
    handleRenderProcessGone(details, () => mainWindow.loadURL(config.url, { userAgent: config.userAgent }));
  });

  mainWindow.on('closed', () => {
    mainWindow = null;
  });

  return mainWindow;
}

function getMainWindow() {
  return mainWindow;
}

function getAvdWindows() {
  return [...avdWindows];
}

module.exports = { createMainWindow, getMainWindow, getAvdWindows, clearSession };
