name: windows-app-for-linux
title: Windows App for Linux
license: MIT
version: '1.0.0'
summary: Unofficial client for Windows App - Access Azure Virtual Desktops on Linux
description: |
  An unofficial standalone Electron application that provides native Linux access to 
  Azure Virtual Desktops via Windows App web access. This unofficial client wraps the 
  Windows Cloud Devices web interface in an Electron shell, configured to behave like 
  Microsoft Edge browser. It enables full access to Azure Virtual Desktop sessions with 
  proper browser emulation, device permissions, and remote desktop support.
contact: https://github.com/mariuszkopowski/windows-app-for-linux
website: https://github.com/mariuszkopowski/windows-app-for-linux
source-code: https://github.com/mariuszkopowski/windows-app-for-linux
issues: https://github.com/mariuszkopowski/windows-app-for-linux/issues
icon: src/windows-app-for-linux.desktop.png

grade: stable
confinement: strict
base: core24

platforms:
  amd64:
    build-on: [amd64]

# Suppress library lint warnings - Electron apps use base snap libraries
lint:
  ignore:
    - library

apps:
  windows-app-for-linux:
    command: bin/electron-launch $SNAP/electron-app/main.js
    desktop: usr/share/applications/windows-app-for-linux.desktop
    plugs:
      - camera
      - audio-playback
      - audio-record
      - network
      - network-bind
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - opengl
      - pulseaudio
      - home
      - removable-media
  update-icon-cache:
    command: bin/update-icon-cache
    plugs:
      - desktop
      - home

parts:
  electron-app:
    plugin: dump
    source: $CRAFT_PROJECT_DIR/src
    # Add required libraries for Electron
    stage-packages:
      - libnss3
      - libatk1.0-0
      - libatk-bridge2.0-0
      - libcups2
      - libdrm2
      - libgbm1
      - libxcomposite1
      - libxdamage1
      - libxfixes3
      - libxkbcommon0
      - libxrandr2
      - libasound2
      - libasound2-plugins
      - libpango-1.0-0
      - libcairo2
      - libatspi2.0-0
      - libgtk-3-0
      - libx11-6
      - libxext6
      - libxrender1
      - libxi6
      - libxtst6
      - libxss1
      - libxinerama1
      - libxcursor1
      - libfontconfig1
      - libfreetype6
      - libpulse0
      - libavahi-client3
      - libavahi-common3
      - libdbus-1-3
      - libgdk-pixbuf-2.0-0
      - libharfbuzz0b
      - libpangoft2-1.0-0
      - libpangocairo-1.0-0
      - libnspr4
      - libxcb1
      - libxau6
      - libxdmcp6
      # OpenGL and Mesa libraries for GPU acceleration
      - libgl1
      - libglx0
      - libgl1-mesa-dri
      - libegl1
      - libegl-mesa0
      - libgles2
      - libglapi-mesa
      - libxshmfence1
      - libxxf86vm1
      # GSettings schemas for GTK
      - gsettings-desktop-schemas
      - libcanberra-gtk3-module
      # GDK-Pixbuf loaders and GTK icon theme
      - libgdk-pixbuf2.0-bin
      - adwaita-icon-theme
      - gtk-update-icon-cache
      - shared-mime-info
      - libgdk-pixbuf2.0-0
    organize:
      '*.js': electron-app/
      '*.json': electron-app/
      '*.png': electron-app/
      '*.desktop': electron-app/
    override-build: |
      craftctl default
      # Remove node_modules if it was copied (we'll install fresh)
      rm -rf "$CRAFT_PART_INSTALL/node_modules" "$CRAFT_PART_INSTALL/electron-app/node_modules" 2>/dev/null || true
      # Install Node.js dependencies
      # Organize step happens, but we need to ensure electron-app directory exists
      cd "$CRAFT_PART_INSTALL"
      # Create electron-app directory and move files there if not already organized
      mkdir -p electron-app
      # Move files to electron-app if they're in the root
      [ -f main.js ] && [ ! -f electron-app/main.js ] && mv *.js electron-app/ 2>/dev/null || true
      [ -f package.json ] && [ ! -f electron-app/package.json ] && mv package.json electron-app/ 2>/dev/null || true
      [ -f package-lock.json ] && [ ! -f electron-app/package-lock.json ] && mv package-lock.json electron-app/ 2>/dev/null || true
      [ -f windows-app-for-linux.desktop.png ] && [ ! -f electron-app/windows-app-for-linux.desktop.png ] && mv windows-app-for-linux.desktop.png electron-app/ 2>/dev/null || true
      [ -f windows-app-for-linux.desktop ] && [ ! -f electron-app/windows-app-for-linux.desktop ] && mv windows-app-for-linux.desktop electron-app/ 2>/dev/null || true
      cd electron-app
      if [ -f package.json ]; then
        # Use npm from the system or install node
        if ! command -v npm &> /dev/null; then
          echo "Installing Node.js..."
          curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
          sudo apt-get install -y nodejs
        fi
        npm install --no-audit --no-fund
        # Remove cross-architecture binaries to avoid GLIBC linting errors
        rm -rf node_modules/7zip-bin/linux/arm node_modules/7zip-bin/linux/arm64 node_modules/7zip-bin/linux/ia32 2>/dev/null || true
      fi
      # Compile GSettings schemas if they exist
      if [ -d "$CRAFT_PART_INSTALL/usr/share/glib-2.0/schemas" ]; then
        if command -v glib-compile-schemas &> /dev/null; then
          glib-compile-schemas "$CRAFT_PART_INSTALL/usr/share/glib-2.0/schemas"
        fi
      fi
      # Update gdk-pixbuf loaders cache if loaders exist
      if [ -d "$CRAFT_PART_INSTALL/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders" ]; then
        if command -v gdk-pixbuf-query-loaders &> /dev/null; then
          mkdir -p "$CRAFT_PART_INSTALL/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0"
          gdk-pixbuf-query-loaders > "$CRAFT_PART_INSTALL/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders.cache" 2>/dev/null || true
        fi
      fi
      # Update icon theme cache if it exists
      if [ -d "$CRAFT_PART_INSTALL/usr/share/icons" ]; then
        if command -v gtk-update-icon-cache &> /dev/null; then
          for theme_dir in "$CRAFT_PART_INSTALL/usr/share/icons"/*; do
            if [ -d "$theme_dir" ] && [ -f "$theme_dir/index.theme" ]; then
              gtk-update-icon-cache -f "$theme_dir" 2>/dev/null || true
            fi
          done
        fi
      fi
      # Copy icon first if it exists (check both current dir and source)
      ICON_COPIED=false
      ICON_SOURCE=""
      if [ -f windows-app-for-linux.desktop.png ]; then
        ICON_SOURCE="windows-app-for-linux.desktop.png"
      elif [ -f "$CRAFT_PROJECT_DIR/windows-app-for-linux.desktop.png" ]; then
        ICON_SOURCE="$CRAFT_PROJECT_DIR/windows-app-for-linux.desktop.png"
      elif [ -f "$CRAFT_PROJECT_DIR/src/windows-app-for-linux.desktop.png" ]; then
        ICON_SOURCE="$CRAFT_PROJECT_DIR/src/windows-app-for-linux.desktop.png"
      fi
      if [ -n "$ICON_SOURCE" ]; then
        # Copy to system pixmaps location
        mkdir -p "$CRAFT_PART_INSTALL/usr/share/pixmaps"
        cp "$ICON_SOURCE" "$CRAFT_PART_INSTALL/usr/share/pixmaps/windows-app-for-linux.png"
        # Also install in hicolor theme structure for better compatibility
        mkdir -p "$CRAFT_PART_INSTALL/usr/share/icons/hicolor/512x512/apps"
        cp "$ICON_SOURCE" "$CRAFT_PART_INSTALL/usr/share/icons/hicolor/512x512/apps/windows-app-for-linux.png"
        # Also copy to snap meta/gui directory (snapcraft checks this first)
        mkdir -p "$CRAFT_PART_INSTALL/meta/gui"
        cp "$ICON_SOURCE" "$CRAFT_PART_INSTALL/meta/gui/icon.png"
        ICON_COPIED=true
      fi
      # Create desktop entry
      mkdir -p "$CRAFT_PART_INSTALL/usr/share/applications"
      if [ "$ICON_COPIED" = "true" ]; then
        cat > "$CRAFT_PART_INSTALL/usr/share/applications/windows-app-for-linux.desktop" << 'EOF'
      [Desktop Entry]
      Name=Windows App for Linux
      Comment=Unofficial client for Windows App - Access Azure Virtual Desktops on Linux
      Exec=windows-app-for-linux
      Icon=windows-app-for-linux
      Type=Application
      Categories=Network;WebBrowser;RemoteAccess;
      EOF
      else
        cat > "$CRAFT_PART_INSTALL/usr/share/applications/windows-app-for-linux.desktop" << 'EOF'
      [Desktop Entry]
      Name=Windows App for Linux
      Comment=Unofficial client for Windows App - Access Azure Virtual Desktops on Linux
      Exec=windows-app-for-linux
      Type=Application
      Categories=Network;WebBrowser;RemoteAccess;
      EOF
      fi
    override-prime: |
      craftctl default
      # Ensure icon is in prime directory for validation (check multiple locations)
      if [ ! -f "$CRAFT_PRIME/usr/share/pixmaps/windows-app-for-linux.png" ]; then
        for ICON_PATH in "$CRAFT_STAGE/usr/share/pixmaps/windows-app-for-linux.png" \
                         "$CRAFT_PART_INSTALL/usr/share/pixmaps/windows-app-for-linux.png" \
                         "$CRAFT_STAGE/meta/gui/icon.png" \
                         "$CRAFT_PART_INSTALL/meta/gui/icon.png"; do
          if [ -f "$ICON_PATH" ]; then
            mkdir -p "$CRAFT_PRIME/usr/share/pixmaps"
            cp "$ICON_PATH" "$CRAFT_PRIME/usr/share/pixmaps/windows-app-for-linux.png"
            # Also ensure hicolor theme icon is present
            mkdir -p "$CRAFT_PRIME/usr/share/icons/hicolor/512x512/apps"
            cp "$ICON_PATH" "$CRAFT_PRIME/usr/share/icons/hicolor/512x512/apps/windows-app-for-linux.png"
            break
          fi
        done
      fi
      # Force update icon cache in prime directory
      if [ -d "$CRAFT_PRIME/usr/share/icons/hicolor" ]; then
        if command -v gtk-update-icon-cache &> /dev/null; then
          gtk-update-icon-cache -f -t "$CRAFT_PRIME/usr/share/icons/hicolor" 2>/dev/null || true
        fi
      fi

  electron-launch:
    plugin: nil
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/bin
      cat > $CRAFT_PART_INSTALL/bin/electron-launch << 'SCRIPTEOF'
      #!/bin/bash
      # electron-launch - Launch Electron app from snap
      set -e
      
      APP_PATH="$1"
      shift || true
      
      # Use the Electron binary directly (not the wrapper script which requires node)
      ELECTRON_BIN="$SNAP/electron-app/node_modules/electron/dist/electron"
      if [ ! -f "$ELECTRON_BIN" ]; then
        echo "Error: Electron binary not found at $ELECTRON_BIN" >&2
        exit 1
      fi
      
      # Set environment variables for Electron
      # CRITICAL: Do NOT set ELECTRON_RUN_AS_NODE=1 (or any value) as it makes Electron run as Node.js
      # Only set it to 0 explicitly, or unset it
      unset ELECTRON_RUN_AS_NODE
      export ELECTRON_IS_DEV=0
      
      # Set library path to include snap libraries, Electron's own libraries, and base snap libraries
      # Electron bundles some libraries in its dist directory and subdirectories
      ELECTRON_LIB_DIR="$SNAP/electron-app/node_modules/electron/dist"
      ELECTRON_LIB_SUBDIR="$ELECTRON_LIB_DIR/lib"
      ELECTRON_SWIFTSHADER_DIR="$ELECTRON_LIB_DIR/swiftshader"
      # Base snap libraries (core24)
      BASE_SNAP_LIB="/snap/core24/current/lib/x86_64-linux-gnu"
      # ALSA plugin dir
      ALSA_LIB_DIR="$SNAP/usr/lib/x86_64-linux-gnu/alsa-lib"
      # Mesa/OpenGL libraries
      MESA_LIB_DIR="$SNAP/usr/lib/x86_64-linux-gnu"
      # GDK-Pixbuf loaders directory
      GDK_PIXBUF_LOADER_DIR="$SNAP/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders"
      # Snap's own libraries from stage-packages (do NOT append host LD_LIBRARY_PATH)
      # Include Electron's dist directory and common subdirectories where it stores libraries like libOSSlib.so
      export LD_LIBRARY_PATH="$ELECTRON_LIB_DIR:$ELECTRON_LIB_SUBDIR:$ELECTRON_SWIFTSHADER_DIR:$SNAP/lib:$SNAP/usr/lib/x86_64-linux-gnu:$SNAP/usr/lib:$ALSA_LIB_DIR:$MESA_LIB_DIR:$GDK_PIXBUF_LOADER_DIR:$BASE_SNAP_LIB"
      
      # Set GSettings schema path for GTK applications
      export XDG_DATA_DIRS="$SNAP/usr/share:$XDG_DATA_DIRS"
      export GSETTINGS_SCHEMA_DIR="$SNAP/usr/share/glib-2.0/schemas"
      
      # Set GDK-Pixbuf module path for GTK icon loading
      export GDK_PIXBUF_MODULEDIR="$SNAP/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders"
      export GDK_PIXBUF_MODULE_FILE="$SNAP/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders.cache"
      
      # Set GTK icon theme path
      export GTK_DATA_PREFIX="$SNAP/usr"
      export GTK_EXE_PREFIX="$SNAP/usr"
      
      # Set mime database path
      export XDG_DATA_HOME="$SNAP/usr/share"
      
      # Change to the app directory so relative paths work
      cd "$SNAP/electron-app"
      
      # Launch Electron directly with the app
      # The Electron binary should initialize Electron runtime, not Node.js
      # Add --no-sandbox flag because SUID sandbox doesn't work in snaps
      # Snaps have their own confinement mechanism
      exec "$ELECTRON_BIN" --no-sandbox "$APP_PATH" "$@"
      SCRIPTEOF
      chmod +x $CRAFT_PART_INSTALL/bin/electron-launch
      
      # Create icon cache update script for manual use
      cat > $CRAFT_PART_INSTALL/bin/update-icon-cache << 'CACHEEOF'
      #!/bin/bash
      # Manual icon cache update script
      # Run: windows-app-for-linux.update-icon-cache
      
      echo "Updating icon cache for Windows App for Linux..."
      
      # Update snap's icon cache
      if [ -d "$SNAP/usr/share/icons/hicolor" ]; then
        if command -v gtk-update-icon-cache >/dev/null 2>&1; then
          echo "Updating snap icon cache..."
          gtk-update-icon-cache -f -t "$SNAP/usr/share/icons/hicolor" 2>/dev/null && echo "✓ Snap icon cache updated" || echo "✗ Failed to update snap icon cache"
        fi
      fi
      
      # Try to update system icon cache (may require permissions)
      if [ -d "/usr/share/icons/hicolor" ]; then
        if command -v gtk-update-icon-cache >/dev/null 2>&1; then
          echo "Updating system icon cache (may require sudo)..."
          sudo gtk-update-icon-cache -f -t "/usr/share/icons/hicolor" 2>/dev/null && echo "✓ System icon cache updated" || echo "✗ Failed to update system icon cache (may need sudo)"
        fi
      fi
      
      # Update desktop database
      if command -v update-desktop-database >/dev/null 2>&1; then
        echo "Updating desktop database..."
        if [ -d "$HOME/.local/share/applications" ]; then
          update-desktop-database "$HOME/.local/share/applications" 2>/dev/null && echo "✓ Desktop database updated" || echo "✗ Failed to update desktop database"
        fi
      fi
      
      echo ""
      echo "Icon cache update complete!"
      echo "If icons still don't update, try:"
      echo "  1. Log out and log back in"
      echo "  2. Restart your desktop environment"
      echo "  3. Run: sudo gtk-update-icon-cache -f -t /usr/share/icons/hicolor"
      CACHEEOF
      chmod +x $CRAFT_PART_INSTALL/bin/update-icon-cache

  icon-cache-hook:
    plugin: nil
    override-build: |
      # Create configure hook to update icon cache on install/update
      mkdir -p $CRAFT_PART_INSTALL/meta/hooks
      cat > $CRAFT_PART_INSTALL/meta/hooks/configure << 'HOOKEOF'
      #!/bin/sh
      # Configure hook - runs on snap install/update
      # Update system icon cache to ensure new icons are recognized
      
      # Update hicolor icon cache if it exists
      if [ -d "$SNAP/usr/share/icons/hicolor" ]; then
        # Try to update icon cache using system gtk-update-icon-cache
        if command -v gtk-update-icon-cache >/dev/null 2>&1; then
          gtk-update-icon-cache -f -t "$SNAP/usr/share/icons/hicolor" 2>/dev/null || true
        fi
      fi
      
      # Also update system-wide icon cache if we have access
      # This requires desktop interface, which we have
      if [ -d "/usr/share/icons/hicolor" ] && [ -w "/usr/share/icons/hicolor" ]; then
        if command -v gtk-update-icon-cache >/dev/null 2>&1; then
          # Update system cache (may require permissions)
          gtk-update-icon-cache -f -t "/usr/share/icons/hicolor" 2>/dev/null || true
        fi
      fi
      
      # Force desktop environment to refresh icon cache
      # Try different methods depending on desktop environment
      if command -v update-desktop-database >/dev/null 2>&1; then
        update-desktop-database "$HOME/.local/share/applications" 2>/dev/null || true
      fi
      
      # Notify desktop environment to refresh (if possible)
      if [ -n "$XDG_CURRENT_DESKTOP" ]; then
        # Try to refresh icon cache via D-Bus (if available)
        if command -v dbus-send >/dev/null 2>&1; then
          dbus-send --session --type=method_call \
            --dest=org.freedesktop.FileManager1 \
            /org/freedesktop/FileManager1 \
            org.freedesktop.DBus.Peer.Ping 2>/dev/null || true
        fi
      fi
      HOOKEOF
      chmod +x $CRAFT_PART_INSTALL/meta/hooks/configure

plugs:
  camera:
    interface: camera
  audio-playback:
    interface: audio-playback
  audio-record:
    interface: audio-record
  network:
    interface: network
  desktop:
    interface: desktop
  wayland:
    interface: wayland
  x11:
    interface: x11
  opengl:
    interface: opengl
  pulseaudio:
    interface: pulseaudio
